### ISSUE TITLE
Javascript prompt doesn't show in some browsers

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#113]
By default, some Web browsers block pop-up prompt and confirmation dialog boxes as a security measure. This will break the save queue functionality (#106). We need to replace this stuff with the usual jquery popup as used elsewhere.

**Comment by DavisNT** [comment]
I will look into this.

Do we have small jQuery popup anywhere? Should we make `prompt()` and `confirm()` popups the same size and style as "track context menu" popups?

**Comment by kingosticks** [comment]
Not sure we gave any that take input. But yes, like the others

**Comment by DavisNT** [comment]
I will **not** fix this (at least for now) as I don't see this as a critical issue (if somebody will want this feature he will disable popup blocker for Pi MusicBox URL) and there is big possibility that my fix won't get merged anyway.
