### ISSUE TITLE
Avoid transferring Track models

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#114]
Mopidy v1.0 API has moved to a lightweight Ref model in many places. This reduces the amount of (often unwanted) data transfered in API calls. You can also pass a list of uris to some methods instead of a list of tracks. This is quicker and prevents bugs such as #49.

The old version of these methods and non uris arguments are now deprecated. I see no need to support older versions of Mopidy so we should rework the webclient to make full use of all these improvements.

**Comment by kingosticks** [comment]
As of musicbox-webclient v2.1.0 the minimum supported version of Mopidy will be v1.1.0

**Comment by jcass77** [comment]
Is this still an issue post v2.1.0? A cursory search of the codebase did not reveal any specific instances where we are still relying on tracks instead of uris / refs.

If you could point me in the right direction then I can perhaps look at converting the relevant API calls?

**Comment by kingosticks** [comment]
Adding to tracklist was probably the biggest offender but that is all different now. Let's close this and reopen if we find something
