### ISSUE TITLE
Tracks selected from the search pane don't play

### ISSUE THREAD

**Issue by colinnuk** [pimusicbox/mopidy-musicbox-webclient#123]
Tracks in the search pane get given a playlist URI of 'trackresultscache' - which obviously doesn't play. This is clearly not a long term fix, but it fixes the issue in the short term by just playing the one track selected.

I have put the below into playTrackByUri in controls.js - it just plays the single track selected.

    var func;
    if(playlist_uri == 'trackresultscache')
       playlist_uri = track_uri;

    func = mopidy.tracklist.add(null, null, playlist_uri);

**Comment by kingosticks** [comment]
This is a duplicate of #109 and it fixed in develop. Release coming soon.
