### ISSUE TITLE
Unplayable tracks in a browse listing cause the incorrect track to be selected

### ISSUE THREAD

**Issue by colinnuk** [pimusicbox/mopidy-musicbox-webclient#124]
Noticed this with SoundCloud, but if there are unplayable tracks (some tracks appear in the liked list but turn out to be 404 errors when you try and use their URIs) in the browse view, then they will be removed from the tracklist in Mopidy. This means that the client side code to play the selected track from the list selects the wrong track as the index doesn't get updated.

The code I changed uses track URI to select the track, rather than incrementing thru a tracklist.

I submitted my change here: https://github.com/colinnuk/mopidy-musicbox-webclient/commit/2eb4141f72ce1ec2ba60b5953ab150d2c9c7b268

But I just realised your develop branch has a rather different function entirely, which could fix the issue?

**Comment by jcass77** [comment]
If you could create a pull request against the latest develop branch then we can probably take another look at this issue?
