### ISSUE TITLE
Can't use contextmenu in browse pane

### ISSUE THREAD

**Issue by puyamn** [pimusicbox/mopidy-musicbox-webclient#126]
Nothing happens, when I click on the 3dot-button. Is this a common issue and does somebody know what the problem is? I'm on version 0.6 and didn't upgrade the webclient or something like that.

**Comment by kingosticks** [comment]
Does the context menu work in the other pages? The context menu was added to the browse page later than the others, just before the 0.6 release in fact (https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/e440dc4d5460a9de321454d92850e7b221f24c3b), so it *should* be present and working.

**Comment by puyamn** [comment]
It works everywhere but with the local files.
