### ISSUE TITLE
Album art is not displayed

### ISSUE THREAD

**Issue by dmosen** [pimusicbox/mopidy-musicbox-webclient#128]
There are failing requests to last.fm for getting the album art. The returned message is always like:
```
    jsonp144560929891147({"error":6,"message":"Album not found","links":[]})
```
This seems to be the case because the request is missing the required artist name:
```
    http://ws.audioscrobbler.com/2.0/?artist=&album=The+Better+Life&method=album.getInfo&api_key=...&callback=jsonp144560929891147&format=json
```
Probably this was caused by a last.fm API change of [album.getInfo](http://www.last.fm/api/show/album.getInfo).

**Comment by kingosticks** [comment]
Also we should probably change to use album art returned from Mopidy where available and perhaps fallback to last.fm.

**Comment by dmosen** [comment]
I analysed this a little deeper - here are my findings:
- this issue does not affect all tracks
- if id3 tag `TPE2` is set a cover is found and displayed

What you get back from Mopidy seems to depend on the MP3's id3 tag:
- if id3 tag `TPE1` is set its value is assigned to the track's artists
- if id3 tag `TPE2` is set its value is assigned to the album's artists

The current implementation relies on the album's artists. Maybe we should first check if there is are artists given for the album and if not retry with the track's artists.

By using the album art returned from Mopidy you mean calling [get_images](https://docs.mopidy.com/en/latest/api/core/?highlight=get_images#mopidy.core.LibraryController.get_images) from the Mopidy Core API?

**Comment by dmosen** [comment]
Another interesting project is [Mopidy-Local-Images](https://github.com/mopidy/mopidy-local-images) which could perhaps be extended to use last.fm for retrieving images and storing them locally. This could be done either in one go on `mopidy scan local` or incrementally when a track is added to the queue.

**Comment by jcass77** [comment]
On a related note, we should also remember to update the web client to rely on ```LibraryController.get_images```, instead of ```Album.images``` which has now been deprecated ( see [#1325](https://github.com/mopidy/mopidy/issues/1325))
