### ISSUE TITLE
cannot seek, fast forward, rewind youtube streams

### ISSUE THREAD

**Issue by jutshanahan** [pimusicbox/mopidy-musicbox-webclient#129]
When a youtube stream is playing, it's desirable to fast forward, rewind or jump to certain times in the youtube stream.  This is especially true if it's an hour long track. 

However, moving the slider around in time has no effect.  Also, when playing a video with a certain time embedded in the url, e.g:  https://youtu.be/i7Zstp8jlgo?t=1272, the stream does not start playing at 1272 seconds as expected.

**Comment by jcass77** [comment]
This appears to be a known issue (see: https://github.com/mopidy/mopidy-youtube/issues/34).

It might be better to track it as part of the Mopidy-Youtube project as I doubt there is much that can be done in the web client to improve this situation.
