### ISSUE TITLE
m3u playlists don't work

### ISSUE THREAD

**Issue by marrem** [pimusicbox/mopidy-musicbox-webclient#131]
I'm running a freshly installed Raspbian Jessie, with mopidy installed with apt-get.
I have placed 2 playlist files in the location set in [m3u] playlists_dir.

    #EXTM3U
    #EXTINF:-1, Studio Brussel
    http://mp3.streampower.be/stubru-high

and the other one

    #EXTM3U
    #EXTINF:-1, Studio Brussel
    tunein:station:s2611

Playing them from a mpd client like MPDroid (Android) works, although the names don't display properly.

They do show up nicely in musicbox-webclient. But when choosing the stream, I don't hear anything and the mopidy log shows:

For both links I get:

```
2015-11-03 18:03:59,358 ERROR [3930:HttpServer] mopidy.http.handlers: WebSocket request error: Expected album to be a <class 'mopidy.models.Album'>, not {u'uri': u'x', u'name': u''}
2015-11-03 18:03:59,395 ERROR [3930:HttpServer] mopidy.http.handlers: WebSocket request error: 
2015-11-03 18:03:59,415 ERROR [3930:HttpServer] mopidy.http.handlers: WebSocket request error: 
```

**Comment by kingosticks** [comment]
I think there is an existing bug for that. Those m3u playlists need an
extra lookup to grab the track data which we do not currently do. Will be
fixed in next release.

**Comment by marrem** [comment]
Hi Nick, thanks for the answer. Then I'll wait for the next release (of musicbox-webclient). In the meantime I'll use a mpd client.

Marc


Nick Steel <notifications@github.com> schreef op 3 november 2015 21:33:12 CET:
>I think there is an existing bug for that. Those m3u playlists need an
>extra lookup to grab the track data which we do not currently do. Will
>be
>fixed in next release.
>On 3 Nov 2015 10:06 am, "marrem" <notifications@github.com> wrote:
>
>> I'm running a freshly installed Raspbian Jessie, with mopidy
>installed
>> with apt-get.
>> I have placed 2 playlist files in the location set in [m3u]
>playlists_dir.
>>
>> #EXTM3U
>> #EXTINF:-1, Studio Brusselhttp://mp3.streampower.be/stubru-high
>>
>> and the other one
>>
>> #EXTM3U
>> #EXTINF:-1, Studio Brussel
>> tunein:station:s2611
>>
>> Playing them from a mpd client like MPDroid (Android) works, although
>the
>> names don't display properly.
>>
>> They do show up nicely in musicbox-webclient. But when choosing the
>> stream, I don't hear anything and the mopidy log shows:
>>
>> For both links I get:
>>
>> 2015-11-03 18:03:59,358 ERROR [3930:HttpServer] mopidy.http.handlers:
>WebSocket request error: Expected album to be a <class
>'mopidy.models.Album'>, not {u'uri': u'x', u'name': u''}
>> 2015-11-03 18:03:59,395 ERROR [3930:HttpServer] mopidy.http.handlers:
>WebSocket request error:
>> 2015-11-03 18:03:59,415 ERROR [3930:HttpServer] mopidy.http.handlers:
>WebSocket request error:
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/131>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/131#issuecomment-153478475

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by marrem** [comment]
I have installed directly from the cloned repo. So I have the dev version now.
Yes the m3u's containing http uri's work fine now.
I also made an m3u containing a bunch of file uris pointing to local media files. At first this didn' t work. The websocket returned a result containing the file url. But somewhere in the java script somehow the results became an array of undefined(s) instead of tracks. 
But then I tried playing a local track and when playing I hit the "get currently playing" button. Then I saw a 'custom' local:track:audio uri. The "Save" button added it to the [Radio Streams.m3u] file. From there I could play it. So knowing how to craft the uris this also works.

Thanks. I can now surprise my wife by compiling some playlists with her favourite tracks.

**Comment by kingosticks** [comment]
Mopidy and musicbox-webclient should both understand file uris (i.e. file://full_path_to_some_file), if you can provide an example of what's not working I can try and take a look. Otherwise this should now all work in develop.

**Comment by Gunbird** [comment]
Is there any progress on this issue ? I am not sure if this is any issue on mopidy side or on musicbox-webclient side ?

Is there another way to listen to m3u stream with mopidy ?

Thanks

**Comment by kingosticks** [comment]
As mentioned above this should be fixed in develop and therefore in the release that followed. 

If there is a further problem then please reopen this or start your own issue with some details i.e. steps to reproduce.
