### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by qurben** [pimusicbox/mopidy-musicbox-webclient#134]
I recently installed letsencrypt on my server, so everything is going to https now. I ran into a few issues when I tried to run the musicbox-webclient behind an https proxy (nginx).

Firstly, the musicbox doesn't even bother about the protocol, `mopidy.js` does however. After I removed line 481 in `mopidy_musicbox_webclient/static/js/gui.js`. It would connect.

There is also a minor problem with lastfm, it uses http to do api calls. This can be fixed by just using the https protocol in `lastfm.api.js`. 

After that there are only mixed content warnings because the lastfm images are loaded with http, but this server does not support https.

I hope I was clear and this can be fixed quickly.

If I have any spare time I'll create a pull request for this.

**Comment by jcass77** [comment]
I don't have letsencrypt installed so can't test this specific usecase. However I believe that the ``websocket_host`` configuration parameter can be used to specify the protocol.

As for changing the last.fm api, it might be best to log the request over at that project's [github repository](https://github.com/fxb/javascript-last.fm-api), and we'd be happy to incorporate a vendor copy of the new api when it becomes available.

Please re-open if there is more to this issue than what I've put forward above.
