### ISSUE TITLE
Clicking Spotify album in search results yields error from getTracksFromUri

### ISSUE THREAD

**Issue by tuftedocelot** [pimusicbox/mopidy-musicbox-webclient#135]
When using the latest from `develop`, I encounter the following error when I try to click on an album returned from Spotify search results:

`Uncaught TypeError: Cannot read property 'length' of undefined` which was caused by library.js at line 306

```
function showAlbum(uri) {
    $('#popupQueue').popup('close');
    $('#popupTracks').popup('close');
    $('#controlsmodal').popup('close');
    $(ALBUM_TABLE).empty();
    //fill from cache
    var pl = getTracksFromUri(uri, true);
    if (pl.length>0) {
```

**Comment by tuftedocelot** [comment]
Brilliant, looks like this is fixed via https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/318a9763f221b31d613b09cd9f35c7d96f566643. Thanks @kingosticks

**Comment by kingosticks** [comment]
Super, thanks for updating this,
