### ISSUE TITLE
Support transition from streamuris to local playlists

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#146]
The favourite stream functionality that was provided by streamuris.js has now been [changed](https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/87ad7fc88041f36d991a2febe828351e402646f6) to utilise Mopidy's native m3u playlist functionality instead. Do we need to provide any sort of upgrade path that converts between the two methods?

**Comment by jcass77** [comment]
What would such an upgrade path entail? I'm not using these features myself at the moment so can't comment on how easy / difficult it would be to do programatically?

At the very least I think we should just provide some guidance on how the conversion can be done by hand, and a notice that 2.1.0 contains breaking changes in this regard.

(perhaps also add an entry for https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/87ad7fc88041f36d991a2febe828351e402646f6 in the changelog - I don't think I picked up on it during the previous review).

**Comment by kingosticks** [comment]
I don't know how non-musicbox users handled it previously. When a new version of the webclient was installed it presumably overwrote any modifications they made to their streamuris file. So perhaps they know to back it up somewhere and then restore it after the upgrade? For these guys we could add a way for them to upload their old streamuris file and then run that through the same convert process as below.

Other people might have had all their modifications saved in each browser (via cookies) and so they didn't have to do anything, it would have just worked.  And so this is the upgrade path that I think is most worth providing. I was thinking along the lines of:
* Showing a convert button/link on the `Streams` page if a streamuris cookie is detected.
* Convert:
  * Loop through the array, and call `addFavourite` for each item
  * Report any problems and then delete the streamuris cookie

**Comment by kingosticks** [comment]
Hmm, might also need to investigate what happens if the user has disabled the m3u extension....

**Comment by kingosticks** [comment]
AND probably bumb our minimum supported version of Mopidy. 0.19 is probably way too old to work with some of the changes I've made. I've personally got no problems with saying the very latest Mopidy release is required. Any brave Musicbox users that are manually updating will have already solved that problem themselves.

**Comment by jcass77** [comment]
Sounds like a non-trivial coding exercise for something that will only be used once :(

**Comment by kingosticks** [comment]
But without this, an upgrading user (who may have previously upgraded without any issues) will suddenly lose their collection of 10 million saved streams. They might be able to find the cookie on their system and recover their streams but I don't think that's acceptable.
