### ISSUE TITLE
Latest webclient requires a newer version of Mopidy than v0.19

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#147]
We currently require at least Mopidy v0.19 but I think with some of the more recent changes that needs to be increased to at least v1.0.

**Comment by jcass77** [comment]
Agreed, I briefly tried and failed to get v0.19.5 going again a few days ago to test something - most all of the extensions require 1.0 anyway.

**Comment by jcass77** [comment]
There are a bunch of M3U fixes in the more recent releases of Mopidy that will probably be beneficial to have for managing the new 'favourites' playlist.

If we bump the dependency to >= 1.0 then everyone will have to [migrate](http://mopidy.readthedocs.org/en/latest/ext/m3u/#migrating-from-mopidy-local-playlists) anyway, so I'm in favour of just insisting on the latest release.

Most of the M3U encoding issues only appear to have been resolved in v1.1 (See [changelog](http://mopidy.readthedocs.org/en/latest/changelog/#v1-1-0-2015-08-09)) - so insisting on v1.1.2 does not feel unreasonable to me.
