### ISSUE TITLE
Default Streams gone after update

### ISSUE THREAD

**Issue by HawkingJan** [pimusicbox/mopidy-musicbox-webclient#167]
Hi,

I recently installed modipy (version 1.1.2) on a RaspberryPi (Raspbian Jessie) and the predefined streams that were shown in the musicbox-webclient worked fine.
I then decided to update some components
```
sudo pip install --upgrade pafy
sudo pip install --upgrade Mopidy-YouTube
sudo pip install --upgrade Mopidy-MusicBox-Webclient
sudo pip install --upgrade youtube_dl
```
and now the stream list in the webclient is empty. Of course I can add my own streams but I wonder if there is a way to get the "default" streams back?

**Comment by kingosticks** [comment]
Hmm no, not currently. I didn't think anyone was actually using the default set since some of them no longer work (for me) and some are geo-locked. I'm not sure how we could distribute the defaults other than re-instating streamuris.js and then letting the conversion code do it's thing. I'm not sure what is the best course of action but maybe having some defaults does make it more obvious that the feature exists.

**Comment by jcass77** [comment]
Yes I agree that the functionality of the ``Streams`` page is a little opaque, and having the defaults there at least gives the user some hint as to how it can be used. 

Just distributing ``streamuris.js`` and converting it the first time that the user opens the page might be the easiest way to get this back in?

**Comment by HawkingJan** [comment]
I would like that. But of course one should check if the "default" streams are working stable and don't use geo-locking. I even used the streams to check that my whole installation is working (there I just needed to click and not even to copy any music files) so it would be bad if the setup is actually fine and it is just an geo-lock issue that prevents hearing any sounds.

**Comment by kingosticks** [comment]
The problem with ensuring a load of default streams still work is something we don't want to support. For a quick test i just randomly click through the tunein browse section and play the first thing I find.

**Comment by kingosticks** [comment]
I think we will stick to the original plan here and not distribute any streams with the web client. It's not really compatible with how the streams are stored any more and it's not really the webclient's job.

But this has highlighted we probably do need something that at least points out the streams functionality is still available (and improved) and just needs populating by the user.

For musicbox, we do have the option of distributing an m3u playlist that's pre-populated with a selection of streams. If we do this we should take better care to choose streams that are reliable and not-geolocked.
