### ISSUE TITLE
Stop creating Mopidy models

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#172]
In at least one place we locally create and populate instances of Mopidy's models ourselves. Previously this idea has led to bugs when we then tried to pass these models back to Mopidy, at which point they turned out to invalid/wrong format/junk. 

I think we now only pass `Ref`s to Mopidy so bugs like this are hopefully gone. However, I can't think of any good reasons why we'd need to create and populate these models ourselves locally and if it's no longer necessary (since we don't use them externally) we should aim to entirely remove this practice. 

One such example of this is at https://github.com/pimusicbox/mopidy-musicbox-webclient/blob/17c8920d6999ee0158054f5019f0156d58eab7cc/mopidy_musicbox_webclient/static/js/functionsvars.js#L241-L250

**Comment by jodal** [comment]
:+1:

**Comment by jcass77** [comment]
I couldn't find any other instances of this apart from what @kingosticks referenced above. Would the relevant statements be identified by searching fro ``__model__``?

**Comment by jodal** [comment]
Yes, that should give them all away.
