### ISSUE TITLE
Vendorize Mopidy.js

### ISSUE THREAD

**Issue by jodal** [pimusicbox/mopidy-musicbox-webclient#175]
Mopidy-Musicbox-Webclient should vendorize a copy of the version of Mopidy.js it supports instead of using `/mopidy/mopidy.min.js` as bundled by Mopidy.

Mopidy's bundled copy of Mopidy.js will be removed in Mopidy 3.0. For background information, please read mopidy/mopidy#1460.

**Comment by jcass77** [comment]
Done. I've gone ahead and pushed https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/34e2abf6129fce36547d58e484d875e2b874591a as this should be a fairly straight forward change to make.

**Comment by jodal** [comment]
That was quick :-)
