### ISSUE TITLE
Update the save queue functionality

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#177]
The queue saving functionality is broken as it tries to create playlists using the 'local' scheme rather than 'm3u' (or 'm3u8'). 
* Tries to create the playlist using the 'local' scheme, which fails.
* Instead then creates the playlist using the next available playlist provider, on my system this happens to be Spotify

Next time, it checks for a 'local' or 'm3u' playlist matching the name and doesn't find one. So creates another unique playlist with the same name (which Spotify has no problem with).

This code also uses the deprecated `PlaylistsController.filter` function.

**Comment by kingosticks** [comment]
The only other thing I was going to suggest with this is that it should probably fail gracefully if the m3u extension is not enabled (like the favourites, I hope). I assume this isn't the case, it'll probably still try and use Spotify.

**Comment by jcass77** [comment]
Could you perhaps point to the section of the code where the favourites handles the case described? I couldn't find it, but should be fairly easy to replicate.

**Comment by kingosticks** [comment]
After inspection it seems by virtue of using `getPlaylistByName` [it is actually handled](https://github.com/pimusicbox/mopidy-musicbox-webclient/blob/c5c74d77f49c43898a9bd6101ef69e912729843f/mopidy_musicbox_webclient/static/js/controls.js#L501) so false alarm.

**Comment by kingosticks** [comment]
In an ideal world the user would get notification that the queue save failed due to this but there are a billion other more important things that could also benefit from this so never mind.
