### ISSUE TITLE
Missing font files

### ISSUE THREAD

**Issue by jjok** [pimusicbox/mopidy-musicbox-webclient#192]
There seem to be some fonts referenced in jquery.mobile.flatui.css that aren't there.

```
"NetworkError: 404 Not Found - http://192.168.1.100/css/fonts/lato-bold.ttf"
lato-bold.ttf
"NetworkError: 404 Not Found - http://192.168.1.100/css/fonts/lato-regular.ttf"
lato-regular.ttf
"NetworkError: 404 Not Found - http://192.168.1.100/css/fonts/lato-italic.ttf"
```

Maybe something to do with this commit 2e874b2f998f79d530783092cd9b4c6f50f69636 where a load of stuff got moved?

**Comment by jcass77** [comment]
Those fonts should all be found under ``vendors/jquery_mobile_flat_ui_theme/fonts/`` and referenced in ``mb.appcache``.

Have you tried clearing **all** of your browser caches?

The path in the error message does not look right - it shouldn't go looking for the fonts in the ``css`` folder so it appears that your MMW installation is somehow still using the old font references from before 2e874b2f998f79d530783092cd9b4c6f50f69636.

**Comment by jjok** [comment]
I've only just started using MusicBox, so there shouldn't be anything cached. I switched over to a different browser to investigate why something else wasn't working and noticed these errors.

**Comment by jcass77** [comment]
How did you install MMW initially? 

My only guess is that there is some version conflict lurking there somewhere (especially if you upgraded any extensions at some point or switched between using ``pip`` and one of the other package management systems for *nix or OS X).

**Comment by jjok** [comment]
I've just installed Pi MusicBox 0.6.0. I haven't made any other changes.

I noticed the error on Windows.

Are those fonts built-in on Mac? That could explain why I see the error, if you're using Mac.

**Comment by jcass77** [comment]
Ah ok, if you are using MB 0.6.0 then you're still on an old version of MMW, which won't have the changes contained in 2e874b2f998f79d530783092cd9b4c6f50f69636.

You could try upgrading to the latest version of MMW but only if you are familiar with the Raspberry Pi platform and comfortable to manually complete some installation steps yourself. 

This will also involve upgrading Mopidy (I recommend at least version 1.1.2). Going all the way to the latest Mopidy 2.0.0 is quite an undertaking with the gstreamer changes that are involved as part of that upgrade path, and will be a little more challenging.

**Comment by jjok** [comment]
OK. Thanks for your help.

There seems to be quite a lot of stuff not working in the version I have. Maybe I'll try and upgrade before reporting anything else.

Do you know if there's an immanent release of MB that contains newer versions of everything?

**Comment by jcass77** [comment]
I'm not aware of any immediate plans for a new MB release, but the topic does come up every so often. It might be best to keep an eye on the forums for the latest: https://discuss.mopidy.com/t/pi-musicbox-with-mopidy-2-0-0-and-jessie/1174
