### ISSUE TITLE
Better spotify browsing support? And TIDAL, Amazon Music support?

### ISSUE THREAD

**Issue by shawaj** [pimusicbox/mopidy-musicbox-webclient#204]
Is it possible to add enhanced support for Spotify so that it makes it easier to navigate/browse by bands/artists/songs etc as the options are fairly limited at present?

Is libspotify still being developed or is that obsolete now? Because having things like Spotify Radio, Spotify Discover, Artists, Albums, related music etc would be extremely useful. i.e. all of the things that spotify has in its own web client

**Comment by jcass77** [comment]
We don't provide any Spotify-specific features here: MMW is a generic web extension for Mopidy.

There are other options that may meet your needs though, perhaps take a look at [Mopidy-Mopify](https://github.com/dirkgroenen/mopidy-mopify).

As far as I know the future of libspotify is uncertain - there should be a discussion on this over at [discuss.mopidy.com](https://discuss.mopidy.com/) or [botbot.me](https://botbot.me/freenode/mopidy/).

**Comment by jcass77** [comment]
...and, there's always [Mopidy SQLite](https://github.com/mopidy/mopidy-local-sqlite) to consider, which provides a few more ways in which to categorize and browse your collection.
