### ISSUE TITLE
Sound distortion

### ISSUE THREAD

**Issue by alesribic73** [pimusicbox/mopidy-musicbox-webclient#206]
Hi

I have instaled mopidy (latest) and HifiBerry DAC+ with MusicBox_WebClient extension
Works fine but when i put slider volume in Web interface above half there is a distortion on DAC output.
I have set digital volume in AlsaMixer v1.0.28 to 25 and then sound is not loud but still distorted.
All changes i made to volume is made in AlsaMixer with command: 
sudo -H -u mopidy alsamixer -D equal and then i select soundcard: snd_rpi_hifiberry_dacplus

My question is which volume does MusicBox_WebClient change? how to limit this volume to 50% ?

**Comment by jcass77** [comment]
Getting the mixer settings exactly right for various hardware setups can be tricky - have you looked at the forums (perhaps https://discuss.mopidy.com/t/settings-for-pimusicbox-0-6-and-hifiberry-dac/1000/5 will be a good place to start)?

My personal setup with the DAC+ is outlined in that forum post and is known to work well.

I'm closing this as the issue log is only used for logging issues with the web client itself, and in this case the problem that you are experiencing is unrelated to MMW.
