### ISSUE TITLE
Use correct hostname in "Trying to reach MusicBox" popup when Mopidy server is unreachable 

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#209]
If a websocket connection cannot be made, the popup message says "Trying to reach MusicBox, please wait". In the case of a non-musicbox install this confusing for the user. It should use the target system's hostname, or a more generic message.

**Comment by jcass77** [comment]
@kingosticks do you think this is as simple as calling ```window.location.hostname``` in JavaScript?

For most users this will probably just return 'localhost' or some sort of IP address.

**Comment by kingosticks** [comment]
I'm not sure, maybe we should just have "Trying to reach Mopidy on $hostname/$ip" ?
