### ISSUE TITLE
Local files playback

### ISSUE THREAD

**Issue by arjunmenon** [pimusicbox/mopidy-musicbox-webclient#211]
Since there is no forum, a quick query.

Can it playback files on the device itself from where the webclient would run, computer, mobile or tablet.

In the website, playback is only mentioned for files on a USB drive **connected** to the Pi or streaming from Spotify.

**Comment by kingosticks** [comment]
No. Like all mopidy clients, it's basically just a remote. All playback occurs on the server so you need some way of getting the music file there.  Mopidy can play music from a DLNA share so you can achieve what you ask if you were to run a DLNA server on your computer/mobile/tablet. 

You can ask general questions at https://discuss.mopidy.com/
