### ISSUE TITLE
option on_track_click doesn't seem to impact on mobile website

### ISSUE THREAD

**Issue by pegelf** [pimusicbox/mopidy-musicbox-webclient#218]
In _/etc/mopidy/mopidy.conf_ I set the option of `on_track_click` to `PLAY_NOW`, because it's very annoing when your whole playlist gets destroyed just because someone misclicked something.

The option seems to work on the desktop website. But when I'm on the mobile website and tap on a song in the search results, it puts every result in the playlist again.

**Comment by kingosticks** [comment]
Have you tried clearing your cache on your mobile browser? There's no
reason for them to behave differently at all.

**Comment by jcass77** [comment]
As mentioned above, it might be necessary to clear your browser cache one your mobile device for this config change to take effect.

Closing this, please re-open if you still experience problems.
