### ISSUE TITLE
Shortened Acces URL

### ISSUE THREAD

**Issue by benjbubu** [pimusicbox/mopidy-musicbox-webclient#233]
Hi everyone,

Is there a way to get a shortened acces url than http://localhost:6680/musicbox_webclient ? 

Thank you for your help

**Comment by kingosticks** [comment]
1. Use a reverse proxy (e.g https://github.com/pimusicbox/pimusicbox/pull/244)

2. Use the deprecated `static_dir` config with a HTML redirection page such as [this](https://github.com/pimusicbox/pimusicbox/blob/65c630a6eb65c7c6837e06deec22e26397b190e7/filechanges/opt/musicbox/webclient/index.html) along with config like this:
```
[http]
static_dir = /opt/musicbox/webclient 
```
