### ISSUE TITLE
Finish implementing playlist support

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#236]
We added some playlist support but not everything. Currently it is not possible to:
* Rename
* Delete 
* Move track positions
* Append tracks to any playlist (only favourites supports this, and only one track at a time from the Streams page.

**Comment by jcass77** [comment]
This may be related to #164, which describes a few additional features that are currently missing.

**Comment by kingosticks** [comment]
That was exactly what I was looking for, I thought it odd we didn't already have an issue for that. Thanks!
