### ISSUE TITLE
Local file search can't handle spaces?

### ISSUE THREAD

**Issue by jemand771** [pimusicbox/mopidy-musicbox-webclient#242]
Hello,

i have set up mopidy for playing my local music library on a raspberry pi. I am not using any other services/sources. Both mopidy and musicbox-webclient are up-to-date.

When I search for a specific song and only search for the first word of the file name, I get the desired result. But if I search for multiple words (eg. the first 2 words of the file name) I always get "No tracks found..."
Somehow the search seems to be struggling with spaces.

Example:

The file is named "The Fray - How To Save A Life (Jiggers Remix)-kp8v--tkqVA.mp3"
The attached screenshots should be self-explaining:
Searching for "How" --> expected result
Searching for "To" --> expected  result
Searching for "kp8v" --> expected  result
Searching for "How To" --> No tracks found

![unbenannt_how](https://cloud.githubusercontent.com/assets/19669567/25958191/50fb0948-3670-11e7-8cf7-1f52db7d2395.png)
![unbenannt_to1](https://cloud.githubusercontent.com/assets/19669567/25958218/5e2f7018-3670-11e7-8d96-8936d359ef44.png)
![unbenannt_to2](https://cloud.githubusercontent.com/assets/19669567/25958221/602e2030-3670-11e7-87d4-b76f17668750.png)
![unbenannt_kp8v](https://cloud.githubusercontent.com/assets/19669567/25958227/66612fec-3670-11e7-94ff-d45bec793eae.png)
![unbenannt_howto](https://cloud.githubusercontent.com/assets/19669567/25958231/6868cc8c-3670-11e7-923b-0990a013bc72.png)

If this is my fault, what am I doing wrong? If not, good luck solving this and thanks for your attention :)

**Comment by kingosticks** [comment]
Works for me. Please post the output of `mopidy deps`

**Comment by jemand771** [comment]
I'm sorry but I can't seem to be able to paste this "in a nice way", so it's just ugly plain text



[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[youtube]
enabled = true

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = true
base_dir = $XDG_MUSIC_DIR
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = false  ; Extension disabled by user config.

[local]
enabled = true
library = json
media_dir = /media/pi/willys/music/
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
  .webm

[musicbox_webclient]
enabled = true
musicbox = false
websocket_host =
websocket_port =
on_track_click = PLAY_ALL

**Comment by kingosticks** [comment]
I always use the sqlite local library. The built-in json library is a bit rough around the edges. If you try switching to that (you'll news to rescan) you should find it's superior. 

If you surround your code in three "tick" characters ````some stuff```` you'll get nice code-style formatting. See https://guides.github.com/features/mastering-markdown/

**Comment by jemand771** [comment]
okay, I will remember that

thank you so much, it now works perfectly :)
