### ISSUE TITLE
mopidy musicbox webclient not apply websocket port from mopidy config

### ISSUE THREAD

**Issue by MurzNN** [pimusicbox/mopidy-musicbox-webclient#244]
I have setup websocket port in /etc/mopidy/mopidy.conf
```
[musicbox_webclient]
enabled = true
musicbox = false
websocket_host = 192.168.1.69
websocket_port = 6680
on_track_click = PLAY_ALL
```
But in web interface I see that it still connecting on 80 port (via nginx proxy): http://i.imgur.com/dbxE4kI.png

Versions are:
- Mopidy (2.1.0)
- Mopidy-MusicBox-Webclient (2.4.0)

Where can be the problem?

**Comment by kingosticks** [comment]
I don't understand what that picture is showing.

**Comment by MurzNN** [comment]
The picture showing that musicbox webclient still connecting to 192.168.1.69:80 instead of  192.168.1.69:6680 ?
As I understand, it must show 192.168.1.69:6680 in connection line?

**Comment by kingosticks** [comment]
It should never use port 80 unless you have told it to, mopidy doesn't listen on port 80 so it wouldn't work anyway. I would double check what it's actually doing (developer console etc) rather than trust that line.

**Comment by MurzNN** [comment]
I have setup nginx proxy at host http://mopidy.example.com:80/ that proxy http://localhost:6680/ interface. So seems that musicbox webclient look at current host and port, and ignore websocket_port from mopidy.conf

**Comment by MurzNN** [comment]
Sorry, in web browser debug console I see that musicbox webclient use normal port (6680), but seems in interface it show port of web server, not web socket. So all works well, sorry for issue.

**Comment by kingosticks** [comment]
I can't remember if that text is supposed to reflect the websocket or Web page connection. I think the latter is more helpful to regular users so it's probably correct as is but I'll check it anyway when I get the chance.
