### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by BboyJemini** [pimusicbox/mopidy-musicbox-webclient#247]
First timer here. I apologize in advance for being vague.
Just popped the image onto my sd card and set up as the manual says, but I can't seem to load anything. 
![image](https://user-images.githubusercontent.com/30486517/28653210-8d5defee-7249-11e7-9f0b-b469bd9def4f.png)
Just keeps saying "Trying to reach Musicbox, please wait."

Tried wifi, everything was enabled correctly, and hard wired in. Nada - same thing.
Just trying to pull music from Spotify - that's it. 

The only thing I've really had to touch in the settings is the wifi settings, and the spotify login. Other than that, everything is as-is. 
Please let me know what I'm doing wrong, and what I can do to fix this. I'd love to have this up and running. This is the first audio "project" I've done with my Pi and want to see what it is capable of. 
Thanks in advance. 

Running a Raspberry Pi model B (yes, old, no doubt)

**Comment by BboyJemini** [comment]
Should have mentioned as well - Running on v0.7.0RC4

**Comment by jiminorris** [comment]
Having the same issue here on Pi2 0.7 RC5. 
Only difference is that I'm playing local (in the SD) music. 
0.6 was working fine, but got a bigger SD and opted for the 0.7 RC when I set it up.

**Comment by kingosticks** [comment]
@BboyJemini, If you have large Spotify playlists it will take a while for the slower Raspberry Pi model B to load them all up the first time. If it's doing this you should see the "Trying to reach..." message flicker on and off. Are you able to login (remotely via SSH or with a keyboard) and take a look at the log files:
* /var/log/mopidy/mopidy.log
* /var/log/musicbox_startup.log

@jiminorris, are you sure it's finished scanning your music collection? Just the contents of /var/log/musicbox_startup.log is probably relevant in your case.

**Comment by BboyJemini** [comment]
Sorry for the delay. Summer holiday and I haven't been on my devices. 


Thanks for the info. I managed to get it working on my pi zero w. I think I'll use the older pi for another project. 


Thanks,


Stu







On Tue, Aug 8, 2017 at 2:19 AM -0700, "Nick Steel" <notifications@github.com> wrote:












@BboyJemini, If you have large Spotify playlists it will take a while for the slower Raspberry Pi model B to load them all up the first time. If it's doing this you should see the "Trying to reach..." message flicker on and off. Are you able to login (remotely via SSH or with a keyboard) and take a look at the log files:

/var/log/mopidy/mopidy.log
/var/log/musicbox_startup.log



@jiminorris, are you sure it's finished scanning your music collection? Just the contents of /var/log/musicbox_startup.log is probably relevant in your case.

**Comment by jcass77** [comment]
Doesn't sound like there's anything more to do here, please re-open if required.
