### ISSUE TITLE
Confusing UI

### ISSUE THREAD

**Issue by kyleknighted** [pimusicbox/mopidy-musicbox-webclient#248]
I'm trying to understand how the UI works.

I have only Spotify configured on Mopidy on a RPi, no local files and no other sources.

I am on a MacBook Pro following these steps

1) Search for the band "The Native Howl"
2) Click on "The Native Howl" under the "Artists" 
3) Click on a single song, it starts playing that song, but it adds every song from every album to the Queue
4) Then if I search for another artist, click on the Artist's name under the header, click any track, and it overwrites the entire Queue with all of the new artist's albums.

How do I search for an artist, look through all their albums, and add only a single track to the Queue?

Mopidy and all plugins/clients/etc were installed with their latest versions as of today.

If you need additional information please let me know.

---

Edit: Just tried on my iPhone and it appears my expected workflow above is functional so i guess there may be a bug in the desktop version?

**Comment by jcass77** [comment]
You need to click on the context menu icon on the right, and select the relevant option for adding the track(s) to the queue:

![skitched-20171007-051702](https://user-images.githubusercontent.com/10268911/31304285-c30881b4-ab1e-11e7-9690-a622283c83e0.png)

and then...

![skitched-20171007-051751](https://user-images.githubusercontent.com/10268911/31304292-dfa6cd76-ab1e-11e7-85ce-be5515682d8c.png)

Also take a look at the ``on_track_click`` parameter as per the configuration section of the  [README](https://github.com/pimusicbox/mopidy-musicbox-webclient#configuration). This parameter sets the default behaviour when just clicking on the track itself (it defaults to ``PLAY_ALL``, which is the behaviour that you described above).

There should be no difference between how the UI behaves when accessed via your browser or your iPhone. If you recently upgraded from a previous version of MMW then you may have to clear the cache on your phone and your browser to ensure consistency.

Please post further usage questions to the Mopidy [discussion forums](https://discuss.mopidy.com/c/pi-musicbox).
