### ISSUE TITLE
Jukebox/Party Mode

### ISSUE THREAD

**Issue by pinwale** [pimusicbox/mopidy-musicbox-webclient#25]
It'll be cool if there was a good support for multiple users. 

It'll be great to allow anyone in the office to search Spotify & queue the songs on the juke box using this web UI.

**Comment by jcass77** [comment]
Also see: https://github.com/mopidy/mopidy/issues/1365.

I think it is more likely that someone will revive one of a number of collaborative web client projects already out there ([dplyr](https://github.com/thechurch/dplyr), [partify](https://github.com/fhats/partify), etc.) before we get around to implementing this in Musicbox-Webclient.
