### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by fscii** [pimusicbox/mopidy-musicbox-webclient#256]
Unless I’m using the setup wrong, I can only get audio to play at the speakers physically connected to the server.  On laptop I chose what to play but it played over the sever speakers when expected behavior is to play where I am not here server is.

**Comment by kingosticks** [comment]
Mopidy plays the music on the server. The webclients are just remotes. You can look at the advanced auto setups section of the Mopidy documentation for a workaround to stream audio but I still don't think it's what you are looking for.
