### ISSUE TITLE
Created irremovable and unplayable playlists

### ISSUE THREAD

**Issue by NathanielJS1541** [pimusicbox/mopidy-musicbox-webclient#262]
I used the bookmark icon in the queue menu to create a new playlist, but I did not realise that m3u was not enabled in my config file. After enabling it, the playlists create and are playable properly. However, I am now stuck with two playlists that I cannot delete, nor locate on my Pi. Here is a screenshot of the playlists in question, along with a properly working playlist that I created as a demonstration.
![PlaylistError](https://user-images.githubusercontent.com/33491104/58045786-70f67e00-7b3b-11e9-833d-b05698f16227.jpg)
"Proper playlist" works correctly, but Test1 and Test12 can't be opened. I am unable to find them located in `/var/lib/mopidy/playlists` (Presumably because m3u was not enabled at the time). You can see that the proper playlist and the irremovable ones also have different icons. I also tried using GMPC to delete the playlists (Which works for playlists that I have created since). However, I get the following error message in GMPC when I try to clear the playlist:  
```
error code 0: ACK [0@0] {playlistclear} Backend with scheme "spotify" failed to save the playlist
```
This error message is the same (replacing {playlistclear} to {rename}) if i try and rename the playlist, and trying to delete it causes the playlists screen to "gray out" and no change is made.  
I have tried uninstalling and purging Mopidy-Spotify and Mopidy-Spotify-Tuingo to no effect.  
  
Without doing a complete reinstall, is there any way for me to remove those playlists? Thanks in advance.

**Comment by kingosticks** [comment]
If I remember correctly, if the m3u backend isn't available it'll use the next backend with playlist support, which looks like it was Spotify. Now, seeing as Spotify playlist support is royally messed up I don't know what happens if you try and create Spotify playlists through mopidy-spotify anymore. Either they did actually get created and you can see (and delete) them in the official Spotify client. Or they failed to sync properly and only exist in the local Spotify cache on your raspberry pi. In which case you will probably need to manually locate that cache data and delete it. According to the readme that should be 'in a "spotify" directory within Mopidy's `core/cache_dir`'.

**Comment by NathanielJS1541** [comment]
Thanks for the quick reply. I've taken a look in the directory and there are two folders and a file.  
The file is called **offline.bnk** and using nano I am not able to find the playlist name there (Using Ctrl+W).  
The **Storage** folder contains a lot of sequentially named folders: e.g. **00**, **04**, **0a** etc. This looks to me like where the queued songs are cached and encrypted?  
The **Users** folder contains an empty folder for my spotify username.  
  
Would I be correct in saying that I should clear the data within the **Storage** folder?

**Comment by kingosticks** [comment]
Yep, delete it all. Anything that is needed should get recreated the next time Mopidy runs, and if it isn't for some reason, just purge and reinstall mopidy-spotify.

**Comment by NathanielJS1541** [comment]
I tried clearing the entire **Storage** directory using `sudo rm -r /var/cache/mopidy/spotify/Storage/*`. I then checked that the directory was empty and rebooted, but the playlists are still listed.

**Comment by NathanielJS1541** [comment]
It's definitely stored somewhere in Mopidy-spotify. I checked by disabling all addons and enabling them one by one until the playlists re-appeared. Ill have a look at other files related to Mopidy-Spotify and see if I can find anything.

**Comment by NathanielJS1541** [comment]
I have managed to resolve my issue, so I'll document my solution in the rare case that this happens to anyone else.  
- First I stopped my mopidy service with `sudo systemctl stop mopidy`. This will be different if you aren't running mopidy as a service, so in this case check the documentation.
- I then cleared the spotify cache as suggested by @kingosticks by running `sudo rm -r /var/cache/mopidy/spotify/Storage/*`.
- I then found another file cache of some description which also needs to be cleared by running `sudo rm -r /var/lib/mopidy/spotify/Users/[USERNAME]/*`
- Finally start your mopidy server again. Since I am running it as a service, this is done with `sudo systemctl stop mopidy`.
After this the playlists have been removed. Thanks for the help @kingosticks!

**Comment by kingosticks** [comment]
There's also some stuff stored in Mopidy's data_dir. Maybe try there? 

Can I also check you have made sure they don't exist in the Spotify official client?

**Comment by kingosticks** [comment]
Ahh great! Sounds like it was in the data_dir.

**Comment by NathanielJS1541** [comment]
Yeah it was. I've just updated my last comment to reflect this more clearly for future reference by others. Thanks again.
