### ISSUE TITLE
Avoid polling for current track and time changes when not playing.

### ISSUE THREAD

**Issue by adamcik** [pimusicbox/mopidy-musicbox-webclient#40]
Mopidy will let you know over the WS when the state changes, so you should be able to get rid of the polling. Ideally you check this type of state once the connection is up to get an initial state, and then after that you just let us emit events to you when things change.

Only exception to this might be that you still want to fetch the time every now and then while playing to avoid drifting, as won't haven't figured out a better solution for this quite yet.

**Comment by adamcik** [comment]
See https://github.com/mopidy/mopidy/issues/434#issuecomment-67977973 for my suggestion on how this could work a bit better.

**Comment by kingosticks** [comment]
Cheers for the reminder, this one drives me nuts but I had completely overlooked it.

**Comment by wagamama** [comment]
I made an integration of media-progress-timer in PR #95.
