### ISSUE TITLE
Click on URI is broken for URIs with ? in

### ISSUE THREAD

**Issue by joemarshall** [pimusicbox/mopidy-musicbox-webclient#62]
I've been messing around making a better local backend for mopidy. One key thing is to return albums and artists in search results, and return sensible browse URIs for them, so you can click on the album name and go to the album.

Now initially, I used the same URIs as in mopidy-local-sqlite for compatibility, 
eg. local:directory?type=artist

However, if you return a URI like this as the URI for an album or artist in the search results, it appears not to work, I had to change them to local:directory/artist/ instead. I suspect there is a quoting issue somewhere here.

**Comment by surfacescan** [comment]
@joemarshall  - So is this something that needs to be changed in mopidy or the web clients?

**Comment by kingosticks** [comment]
Are there steps I can do to reproduce this?

**Comment by joemarshall** [comment]
The spotify URI is "spotify:album:ID", so will happily sit after a ? in a web URL without HTML encoding.

The local-sqlite URI for an artist is like "local:directory?type=artist/ARTISTNAME"

ie. it has ? = and / in it, so for it to sit on a web URL it needs HTML encoding and decoding.

At some point soon, local-sqlite will be fixed so it returns albums / artists from search as well as tracks, and then this will be a problem for it.

Does that make sense?

I suspect you can reproduce it by going to http://192.168.1.96/musicbox_webclient/#artists? and adding a valid mopidy local sqlite artist URI at the end of it, if you fix the bug, it should list the albums by that artist.

**Comment by jcass77** [comment]
I'm not sure I can follow the history here - will this require encoding a query string so that it can be embedded in another query string?

@joemarshall is this still something that you are interested in seeing changed in the web client?

**Comment by jcass77** [comment]
We haven't had any more feedback on this issue and I am not sure that it can be classified as a 'bug' in MMW.

Please reopen if anybody would like to re-open the discussion.
