### ISSUE TITLE
Scroll to currently playing song when viewing the queue

### ISSUE THREAD

**Issue by EHLOVader** [pimusicbox/mopidy-musicbox-webclient#71]
I feel like it would make sense to scroll down to the current song in the queue.

**Comment by kingosticks** [comment]
I'm not sure I'd want it to jump down to that position every time I
navigate to the queue, it might be a bit annoying. How about a button that
takes you there instead?

**Comment by EHLOVader** [comment]
Sure. The basic gist of how I expected it to work is to always have the current song on top of the queue (as queues tend to work), and would also be solved if #70 were put into place such as when playing a song from the queue removed it from the list and offloaded it into a history of what had been played.

**Comment by EHLOVader** [comment]
I guess also a clear played button might work. I imagined a whole day (or more) of this playing at the office and the queue becoming unmanageably long and hard to pin down the currently playing song or what remains.

**Comment by kingosticks** [comment]
Despite its name it's not really a queue, IIRC it's the current tracklist.
And Mopidy doesn't remove a track from the tracklist once played unless
consume is enabled. It sounds like you probably want to enable consume, and
then if the playback history is added somewhere, then you've got more of a
queue setup.

**Comment by EHLOVader** [comment]
Sorry, yes that would be an amazing addition. Thank you for figuring out what it was I really wanted.

Still learning about Mopidy having just found it. Hopefully I will be able to contribute in a constructive way soon.

**Comment by kingosticks** [comment]
Once v0.20 of Mopidy is released (with playback History support) we'll take a look at this.

**Comment by kingosticks** [comment]
By 'this' I meant the history part.  Is scrolling the tracklist to the currently playing track (on demand) still interesting do you think, @EHLOVader ?

**Comment by EHLOVader** [comment]
Ah, when I saw the reply I thought it was on #70. I think it would still be useful but maybe I will see how it works using it as it stands. Thanks for considering these.

**Comment by jcass77** [comment]
I don't thnk there is anything to do here, apart from taking another look at #70 once Mopidy provides some event triggers for monitoring the history.
