### ISSUE TITLE
Ability to add youtube, mp3s or other streams to queue instead of playing immediately.

### ISSUE THREAD

**Issue by EHLOVader** [pimusicbox/mopidy-musicbox-webclient#75]
I would like the ability to add to queue instead of playing especially with youtube so they can play next in line.

![streams](https://i.imgur.com/SglGSsul.png)

**Comment by kingosticks** [comment]
Just to clarify, you want to be able to queue up an arbitrary stream rather than something you browsed/searched to?

**Comment by EHLOVader** [comment]
Yes. The browse functions were fixed in e440dc4 according to the issue I posted on that. And the add album was addressed in #69 although interface wise it may make more sense on the album itself instead of in the menu. 

For a use case, occasionally I will want to queue up a Youtube song, or an MP3 directly from a site like http://musicforprogramming.net/

I have even had a few instances where it would be easier to put in the spotify uri or soundcloud url instead of searching for it, because I have found searching doesn't always work as well as I had hoped.

**Comment by icerfish** [comment]
This would be a much used feature, as it is easier to get a Spotify URI from Spotify directly than it is to search through it on the UI.

**Comment by kingosticks** [comment]
Does anyone have any ideas of a nice way to integrate this into the UI? I personally think it would be better to somehow make this available from the Queue page itself, rather than cluttering the Streams page with even more buttons (plus, I am trying to get rid of the Streams page entirely).

**Comment by jcass77** [comment]
@kingosticks do you still want to get rid of the streams page? I think it is fairly useful although there is some overlap in having streams show up in the 'Musicbox Favourites' playlist as well - is that what is bothering you?

In terms of implementing in the UI: we can probably use a variation of the new tracklist popup menus where the button will execute the ``onClick`` action and the ellipses is displayed somewhere next to it? Alternatively, adding another [select menu](http://demos.jquerymobile.com/1.3.2/widgets/selects/) containing the various options might be the more standard approach, but will take up more space.

**Comment by kingosticks** [comment]
I'm not sure. Yes, now that streamuris is just another playlist it seems slightly odd to give it it's own page. But the other functionality on the page is quite useful so we don't want to lose it. 

UI wise for this feature: we could change the 'play' button to a 'lookup' button. Clicking it would display a list of tracks, complete with a popup menu etc, just like everywhere else. The popup menu could then provide the "save/add to playlist" option (and it would be nice if this was on all popup menus). How does that sound?

**Comment by jcass77** [comment]
I think I understand what you're aiming for. It basically means adding a 'Add to Favourites' option to the popup menus, which becomes 'Remove from Playlist' if the track is already part of a playlist.

![skitched-20160426-063045](https://cloud.githubusercontent.com/assets/10268911/14807026/74826434-0b78-11e6-9f2f-20bf61bfe6ab.png)

I'd like to combine this with #164, by adding a separate popup menu for the actual playlists that can be used to delete entire lists as well.

We can then just re-use the above functionality on the Streams page by doing a lookup on the URI first, and then displaying the track(s) for that URI in a list with the popup menu attached to it.

**Comment by kingosticks** [comment]
Yes but do we need #164 for this? This is all tracklist popup stuff.
