### ISSUE TITLE
Add contextual favicon to indicate play pause or other states.

### ISSUE THREAD

**Issue by EHLOVader** [pimusicbox/mopidy-musicbox-webclient#77]
A library like this might be nice to add badges or icons to the favicon for various states of the player.

[http://lab.ejci.net/favico.js/](http://lab.ejci.net/favico.js/)

**Comment by kingosticks** [comment]
Sounds fun but I won't be getting much around to this any time soon.

**Comment by jcass77** [comment]
I couldn't get the demos to work on my IOS devices, and as we are committed to cross platform support this might be something that we hold off on until something similar is available in jQuery Mobile.
