### ISSUE TITLE
Add HTML5 notifications for quick access to currently playing or song switches.

### ISSUE THREAD

**Issue by EHLOVader** [pimusicbox/mopidy-musicbox-webclient#78]
General popup notifications with newer HTML5 api to pop up outside of the browser window.

Possible library for this feature:
[https://github.com/ttsvetko/HTML5-Desktop-Notifications](https://github.com/ttsvetko/HTML5-Desktop-Notifications)

**Comment by jcass77** [comment]
The referenced project has been [deprecated](https://github.com/ttsvetko/HTML5-Desktop-Notifications/commit/1c3fc78c75df8ff24accf51f8dcef91762ef9d7c) and it is not immediately apparent if a good, well maintained, alternative is available that is both platform and browser independent.

We can revisit this if the situation changes but for now it is not something that I think we will be spending time on.
