### ISSUE TITLE
Use explicit Mopidy.js calling convention

### ISSUE THREAD

**Issue by jodal** [pimusicbox/mopidy-musicbox-webclient#79]
In Mopidy.js 0.4 / Mopidy 0.19 a new "calling convention" setting was added to Mopidy.js. See https://docs.mopidy.com/en/latest/api/js/#creating-an-instance for details.

It seems MusicBox-Webclient still doesn't explicitly set the calling convention of Mopidy.js, so it defaults to "by-position-only". This default will change in the future, and when that happens, MusicBox-Webclient will break as is.

In the Mopidy.js docs, there's some motivation for changing to the new alternative calling convention, "by-position-or-by-name". The migration to it can be as simple as adding `[]` brackets around all existing Mopidy.js calls.

**Comment by kingosticks** [comment]
Great, nice work.
