### ISSUE TITLE
Add sleep timer

### ISSUE THREAD

**Issue by teq0** [pimusicbox/mopidy-musicbox-webclient#91]
I've submitted a PR to mopidy - https://github.com/mopidy/mopidy/pull/1085 - to add a sleep timer. If it gets accepted I've also written an extension for MusicBox Webclient to control it - https://github.com/teq0/Mopidy-MusicBox-Webclient/tree/feature/sleeptimer.

I've written it as a self-executing function so that the code is completely encapsulated, which keeps it nice and clean but it's quite a different style to the rest of the MusicBox Webclient. Should I refactor it into the more global style of the rest of the code? I'm not exactly sure where the various bits should go.

**Comment by jcass77** [comment]
Update: it appears that the Mopidy PR referenced above ultimately wasn't merged.

@DavisNT , this sounds like a useful feature to consider adding to [Mopidy-AlarmClock](https://github.com/DavisNT/mopidy-alarmclock)?

**Comment by jcass77** [comment]
It does not appear as if the idea to develop a sleep timer extension for Mopidy was ever taken any further.

Should one become available in the future, then we should be able to integrate it in the web client fairly easily. For now though I think it is unlikely that this is something that we will build ourselves.

**Comment by jcass77** [comment]
Closing this in favour of this feature going into Mopidy-AlarmClock (see: https://github.com/DavisNT/mopidy-alarmclock/issues/4).
